build:
    nodes:
        analysis:
            tests:
                override: 
                  - golint-run
filter:
    excluded_paths:
        - integration/
    dependency_paths:
        - vendor/
tools:
    external_code_coverage: true
